#------------------------------ Logo ------------------------------

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);

logo.sprite.SetX(
    Window.GetWidth() / 2 -
    logo.image.GetWidth() / 2
);
logo.sprite.SetY(
    Window.GetHeight() / 2 -
    logo.image.GetHeight() / 2
);

#------------------------------ Spinner ------------------------------

spinner.frame = 0;

spinner.images[0] = Image("spinner-0001.png");
spinner.images[1] = Image("spinner-0002.png");
spinner.images[2] = Image("spinner-0003.png");
spinner.images[3] = Image("spinner-0004.png");
spinner.images[4] = Image("spinner-0005.png");
spinner.images[5] = Image("spinner-0006.png");
spinner.images[6] = Image("spinner-0007.png");
spinner.images[7] = Image("spinner-0008.png");
spinner.images[8] = Image("spinner-0009.png");
spinner.images[9] = Image("spinner-0010.png");
spinner.images[10] = Image("spinner-0011.png");
spinner.images[11] = Image("spinner-0012.png");
spinner.images[12] = Image("spinner-0013.png");
spinner.images[13] = Image("spinner-0014.png");
spinner.images[14] = Image("spinner-0015.png");
spinner.images[15] = Image("spinner-0016.png");
spinner.images[16] = Image("spinner-0017.png");
spinner.images[17] = Image("spinner-0018.png");
spinner.images[18] = Image("spinner-0019.png");
spinner.images[19] = Image("spinner-0020.png");
spinner.images[20] = Image("spinner-0021.png");
spinner.images[21] = Image("spinner-0022.png");
spinner.images[22] = Image("spinner-0023.png");
spinner.images[23] = Image("spinner-0024.png");
spinner.images[24] = Image("spinner-0025.png");
spinner.images[25] = Image("spinner-0026.png");
spinner.images[26] = Image("spinner-0027.png");
spinner.images[27] = Image("spinner-0028.png");
spinner.images[28] = Image("spinner-0029.png");
spinner.images[29] = Image("spinner-0030.png");

spinner.sprite = Sprite(spinner.images[0]);

spinner.sprite.SetX(
    Window.GetWidth() / 2 -
    spinner.images[0].GetWidth() / 2
);
spinner.sprite.SetY(
    logo.sprite.GetY() +
    logo.image.GetHeight() +
    40
);

fun update_spinner() {
    spinner.frame++;
    spinner.frame %= 30;

    spinner.sprite.SetImage(
        spinner.images[spinner.frame]
    );
}

#------------------------------ Message ------------------------------

message.sprite = Sprite();
message.sprite.SetOpacity(0);

message.sprite.SetX(0);
message.sprite.SetY(
    spinner.sprite.GetY() +
    spinner.images[0].GetHeight() +
    30
);

fun display_message_callback(text) {
    message.image = Image.Text(text, 1, 1, 1);
    message.sprite.SetImage(message.image);

    message.sprite.SetX(
        Window.GetWidth() / 2 -
        message.image.GetWidth() / 2
    );

    message.sprite.SetOpacity(1);
}

fun hide_message_callback(text) {
    message.sprite.SetOpacity(0);
}

Plymouth.SetDisplayMessageFunction(display_message_callback);
Plymouth.SetHideMessageFunction(hide_message_callback);

#------------------------------ Refresh ------------------------------

fun refresh_callback() {
    update_spinner();
}

Plymouth.SetRefreshFunction(refresh_callback);
