config_version = 14

[bar]
order = [ "default", "bottom" ]

    [bar.default]
    position = "top"
    background_opacity = 0.0
    capsule = true
    capsule_opacity = 0.9
    capsule_padding = 8.0
    capsule_thickness = 0.85
    margin_ends = 0
    radius = 0
    reserve_space = false
    shadow = false
    start = [ ]
    center = [ "group:g1" ]
    end = [ "group:g2", "group:g3" ]

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "clock", "notifications", "privacy" ]
        opacity = 0.9
        padding = 8.0

        [[bar.default.capsule_group]]
        accordion = true
        accordion_direction = "start"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "temp", "cpu", "GPU", "ram", "sysmon" ]
        opacity = 0.9
        padding = 8.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "start"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "bluetooth", "network", "battery" ]
        opacity = 0.9
        padding = 8.0
        widget_spacing = 8

    [bar.bottom]
    position = "bottom"
    background_opacity = 0.0
    capsule = true
    capsule_opacity = 0.9
    capsule_padding = 8.0
    capsule_thickness = 0.85
    margin_ends = 0
    radius = 0
    reserve_space = false
    shadow = false
    start = []
    center = [ "group:g1" ]
    end = [ "media" ]

        [[bar.bottom.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "workspaces", "tray" ]
        opacity = 0.9
        padding = 8.0
        widget_spacing = 12

[control_center]
hidden_tabs = [ "monitor", "weather" ]

    [control_center.calendar]
    show_events_card = false
    show_week_numbers = true

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000005", "desktop-widget-0000000000000006" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 208.0
    box_width = 496.0
    cx = 800.0
    cy = 180.0
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        background = false
        center_text = true
        circle = true
        clock_style = "digital"
        shadow = true

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 240.0
    box_width = 624.0
    cx = 1720.0
    cy = 272.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        background = false
        center_text = true
        circle = true
        clock_style = "digital"
        shadow = true

[dock]
enabled = true
icon_size = 20
position = "right"
reserve_space = false
smart_auto_hide = true

[idle]
behavior_order = [ "idle-behavior", "lock" ]
pre_action_fade_seconds = 5

    [idle.behavior.idle-behavior]
    action = "screen_off"
    enabled = true
    timeout = 300.0

[location]
address = "Sweden"
auto_locate = false

[lockscreen]
allow_empty_password = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 150.0
    box_width = 810.0
    cx = 1720.0
    cy = 1258.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 0.97
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 150.0
    box_width = 810.0
    cx = 800.0
    cy = 818.0
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 0.97
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 208.0
    box_width = 496.0
    cx = 800.0
    cy = 180.0
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 800.0
    cy = 948.0
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = 0.0
    type = "yocraft/battery-widget:widget"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = true
        layout = "horizontal"
        show_glyph = true
        show_label = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 240.0
    box_width = 624.0
    cx = 1720.0
    cy = 272.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        center_text = true

[nightlight]
enabled = true
temperature_night = 3000

[notification]
history_retention_hours = 24
layer = "overlay"
background_opacity = 0.9
offset_y = 40
position = "top_center"

[osd]
position = "bottom_center"
background_opacity = 0.9
offset_y = 40

[plugin_settings."ezequiel/mango_layouts"]
panel_open_near_click = true
panel_placement = "attached"
panel_position = "auto"
show_deck = false
show_grid = false
show_monocle = false
show_vertical_deck = false
show_vertical_fair = false
show_vertical_grid = false
show_vertical_tile = false

[plugins]
enabled = [ "ezequiel/mango_layouts", "yocraft/battery-widget" ]

[shell]
avatar_path = "/home/jonwin/nixos-jonwin/modules/system/hypr/lock/logo.png"
clipboard_history_max_entries = 1000
clipboard_image_action_command = "satty -f -"
font_family = "FiraCode Nerd Font"
lang = "sv"
screen_time_enabled = true

    [shell.panel]
    control_center_placement = "floating"
    wallpaper_placement = "floating"
    session_placement = "floating"
    session_position = "center"

    [shell.screenshot]
    directory = "~/Pictures/screenshots"

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "mango" ]
    community_ids = [ "zen-browser" ]

[wallpaper]
directory = "/home/jonwin/Pictures/wallpaper"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/jonwin/Pictures/wallpaper/20260801_164314.jpg"

[weather]
enabled = false

[widget.GPU]
show_value = false
stat = "gpu_usage"
type = "sysmon"
interactive = false

[widget.battery]
display_mode = "graphic"
show_label = false
interactive = false

[widget.bluetooth]
hide_when_no_connected_device = true
interactive = false

[widget.btn]
type = "ezequiel/mango_layouts:btn"

[widget.clock]
tooltip_format = "{:%A %d %B %Y}\\n{:%x v.%V}"
interactive = false

[widget.cpu]
show_value = false
interactive = false

[widget.media]
max_length = 300
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
show_label = false
interactive = false

[widget.notifications]
hide_when_no_unread = true
interactive = false

[widget.privacy]
hide_inactive = true
interactive = false

[widget.ram]
show_value = false
interactive = false

[widget.sysmon]
show_value = false
stat = "disk_used_pct"
interactive = false

[widget.temp]
show_value = false

    [widget.temp.actions]
    left = "none"
    middle = "none"

[widget.tray]
hide_passive = false

[widget.workspaces]
active_pill_size = 2.0
focused_output_only = true
hide_when_empty = true
interactive = false
scale = 1.1
show_labels = false
style = "focus_hint"
