#!/usr/bin/env sh

status="$(cat /sys/class/power_supply/BAT0/status)"
level="$(cat /sys/class/power_supply/BAT0/capacity)"

CRIT='\033[0;31m'
WARN='\033[0;33m'
NC='\033[0m'

if [[ ("$status" == "Discharging") || ("$status" == "Full") ]]; then
  if [[ "$level" -le "5" ]]; then
    printf "${CRIT}󰂎 $level%%${NC}"
  elif [[ ("$level" -ge "5") && ("$level" -le "15") ]]; then
    printf "${WARN}󰁺 $level%%${NC}"
  elif [[ ("$level" -ge "15") && ("$level" -le "25") ]]; then
    printf "󰁻 $level%%"
  elif [[ ("$level" -ge "25") && ("$level" -le "35") ]]; then
    printf "󰁼 $level%%"
  elif [[ ("$level" -ge "35") && ("$level" -le "45") ]]; then
    printf "󰁽 $level%%"
  elif [[ ("$level" -ge "45") && ("$level" -le "55") ]]; then
    printf "󰁾 $level%%"
  elif [[ ("$level" -ge "55") && ("$level" -le "65") ]]; then
    printf "󰁿 $level%%"
  elif [[ ("$level" -ge "65") && ("$level" -le "75") ]]; then
    printf "󰂀 $level%%"
  elif [[ ("$level" -ge "75") && ("$level" -le "85") ]]; then
    printf "󰂁 $level%%"
  elif [[ ("$level" -ge "85") && ("$level" -le "95") ]]; then
    printf "󰂂 $level%%"
  elif [[ ("$level" -ge "95") ]]; then
    printf "󰁹 $level%%"
  fi
elif [[ "$status" == "Charging" ]]; then
  printf "󰂄 $level%%";
fi
